In [118]:
import numpy as np
import pandas as pd
from datetime import datetime,date
# Saved Tiingo API Token in 'token' variable in apiToken.py file
from apiToken import token

In [141]:
# Getting prices from Tiingo
def getPrice(token,ticker,startDate,endDate):
    return pd.read_csv('https://api.tiingo.com/tiingo/daily/'+ticker+'/prices?startDate='+startDate+'&endDate='+endDate+'&token='+token+'&format=csv')
today = str(date.today())
bndPrice = getPrice(token,'bnd','2019-08-29',today)
bndxPrice = getPrice(token,'bndx','2019-08-30',today)
vtiPrice = getPrice(token,'vti','2019-08-30',today)
vxusPrice = getPrice(token,'vxus','2019-08-30',today)
vtiPrice['returns'] = (vtiPrice.close+vtiPrice.divCash)/vtiPrice.close.shift(1) - 1
vxusPrice['returns'] = (vxusPrice.close+vxusPrice.divCash)/vxusPrice.close.shift(1) - 1
bndPrice['returns'] = (bndPrice.close+bndPrice.divCash)/bndPrice.close.shift(1) - 1
bndxPrice['returns'] = (bndxPrice.close+bndxPrice.divCash)/bndxPrice.close.shift(1) - 1
bndPrice = bndPrice.loc[:,['date','returns']]
bndxPrice = bndxPrice.loc[:,['date','returns']]
vtiPrice = vtiPrice.loc[:,['date','returns']]
vxusPrice = vxusPrice.loc[:,['date','returns']]

In [153]:
getPrice(token,'bnd','2019-08-29',today)

date  close   high    low     open   volume   adjClose    adjHigh  \
0    2019-08-29  85.11  85.12  84.95  85.1200  2812400  83.023376  83.033131   
1    2019-08-30  85.10  85.17  85.00  85.0300  2861800  83.013621  83.081905   
2    2019-09-03  84.99  85.18  84.84  84.9800  3345800  83.089902  83.275654   
3    2019-09-04  85.15  85.16  84.95  84.9700  2864100  83.246325  83.256101   
4    2019-09-05  84.71  84.90  84.58  84.8500  3162800  82.816162  83.001914   
..          ...    ...    ...    ...      ...      ...        ...        ...   
231  2020-07-30  89.34  89.37  89.30  89.3200  2621231  89.181418  89.211364   
232  2020-07-31  89.46  89.47  89.27  89.3485  5110509  89.301205  89.311187   
233  2020-08-03  89.27  89.33  89.17  89.3200  6270005  89.270000  89.330000   
234  2020-08-04  89.46  89.46  89.35  89.3700  5325101  89.460000  89.460000   
235  2020-08-05  89.34  89.39  89.28  89.3700  4931693  89.340000  89.390000   

        adjLow    adjOpen  adjVolume   divCash  splitFactor  
0    82.867299  83.033131    2812400  0.000000          1.0  
1    82.916073  82.945337    2861800  0.000000          1.0  
2    82.943256  83.080126    3345800  0.188198          1.0  
3    83.050796  83.070349    2864100  0.000000          1.0  
4    82.689068  82.953032    3162800  0.000000          1.0  
..         ...        ...        ...       ...          ...  
231  89.141489  89.161453    2621231  0.000000          1.0  
232  89.111542  89.189902    5110509  0.000000          1.0  
233  89.170000  89.320000    6270005  0.158740          1.0  
234  89.350000  89.370000    5325101  0.000000          1.0  
235  89.280000  89.370000    4931693  0.000000          1.0  

[236 rows x 13 columns]

In [142]:
# Reading saved data (Market cap is in billions)
vti = pd.read_csv('Data/vti_MC_Data.csv')
vxus = pd.read_csv('Data/vxus_MC_Data.csv')
bnd = pd.read_csv('Data/bnd_MC_Data.csv')
bndx = pd.read_csv('Data/bndx_MC_Data.csv')

In [149]:
df = vtiPrice.rename(columns={"returns":"VTI_Return"}).merge(vxusPrice.rename(columns={"returns":"VXUS_Return"}),on='date',how='outer').merge(bndPrice.rename(columns={"returns":"BND_Return"}),on='date',how='outer').merge(bndxPrice.rename(columns={"returns":"BNDX_Return"}),on='date',how='outer').merge(vti.rename(columns={"Market Cap":"VTI_MarketCap"}),on='date',how='outer').merge(vxus.rename(columns={"Market Cap":"VXUS_MarketCap"}),on='date',how='outer').merge(bnd.rename(columns={"Market Cap":"BND_MarketCap"}),on='date',how='outer').merge(bndx.rename(columns={"Market Cap":"BNDX_MarketCap"}),on='date',how='outer').sort_values(by='date').reset_index(drop=True)
df.head(100)

date  VTI_Return  VXUS_Return  BND_Return  BNDX_Return  \
0   2012-03-30         NaN          NaN         NaN          NaN   
1   2012-06-29         NaN          NaN         NaN          NaN   
2   2012-09-28         NaN          NaN         NaN          NaN   
3   2012-12-31         NaN          NaN         NaN          NaN   
4   2013-03-28         NaN          NaN         NaN          NaN   
..         ...         ...          ...         ...          ...   
95  2019-11-29   -0.004479    -0.008817    0.000000    -0.001716   
96  2019-11-30         NaN          NaN         NaN          NaN   
97  2019-12-02   -0.009061    -0.004077   -0.002610    -0.002581   
98  2019-12-03   -0.005928    -0.003349    0.005364     0.003106   
99  2019-12-04    0.006471     0.008588   -0.002016    -0.001376   

    VTI_MarketCap  VXUS_MarketCap  BND_MarketCap  BNDX_MarketCap  
0       15480.583             NaN            NaN             NaN  
1       14909.819             NaN            NaN             NaN  
2       15550.575             NaN            NaN             NaN  
3       15758.775             NaN            NaN             NaN  
4       17365.598             NaN            NaN             NaN  
..            ...             ...            ...             ...  
95            NaN       24591.817            NaN             NaN  
96            NaN             NaN       22522.29        19350.73  
97            NaN             NaN            NaN             NaN  
98            NaN             NaN            NaN             NaN  
99            NaN             NaN            NaN             NaN  

[100 rows x 9 columns]

In [152]:
df[df.VTI_Return.isnull()]

date  VTI_Return  VXUS_Return  BND_Return  BNDX_Return  \
0    2012-03-30         NaN          NaN         NaN          NaN   
1    2012-06-29         NaN          NaN         NaN          NaN   
2    2012-09-28         NaN          NaN         NaN          NaN   
3    2012-12-31         NaN          NaN         NaN          NaN   
4    2013-03-28         NaN          NaN         NaN          NaN   
5    2013-06-28         NaN          NaN         NaN          NaN   
6    2013-09-30         NaN          NaN         NaN          NaN   
7    2013-12-31         NaN          NaN         NaN          NaN   
8    2014-03-31         NaN          NaN         NaN          NaN   
9    2014-06-30         NaN          NaN         NaN          NaN   
10   2014-09-30         NaN          NaN         NaN          NaN   
11   2014-12-31         NaN          NaN         NaN          NaN   
12   2015-03-31         NaN          NaN         NaN          NaN   
13   2015-06-30         NaN          NaN         NaN          NaN   
14   2015-09-30         NaN          NaN         NaN          NaN   
15   2015-12-31         NaN          NaN         NaN          NaN   
16   2016-03-31         NaN          NaN         NaN          NaN   
17   2016-06-30         NaN          NaN         NaN          NaN   
18   2016-09-30         NaN          NaN         NaN          NaN   
19   2016-12-30         NaN          NaN         NaN          NaN   
20   2017-03-31         NaN          NaN         NaN          NaN   
21   2017-06-30         NaN          NaN         NaN          NaN   
22   2017-09-29         NaN          NaN         NaN          NaN   
23   2017-12-29         NaN          NaN         NaN          NaN   
24   2018-03-29         NaN          NaN         NaN          NaN   
25   2018-06-29         NaN          NaN         NaN          NaN   
26   2018-09-28         NaN          NaN         NaN          NaN   
27   2018-12-31         NaN          NaN         NaN          NaN   
28   2019-03-29         NaN          NaN         NaN          NaN   
29   2019-06-28         NaN          NaN         NaN          NaN   
30   2019-08-29         NaN          NaN         NaN          NaN   
31   2019-08-30         NaN          NaN   -0.000117          NaN   
32   2019-08-31         NaN          NaN         NaN          NaN   
96   2019-11-30         NaN          NaN         NaN          NaN   
158  2020-02-29         NaN          NaN         NaN          NaN   
222  2020-05-31         NaN          NaN         NaN          NaN   

     VTI_MarketCap  VXUS_MarketCap  BND_MarketCap  BNDX_MarketCap  
0        15480.583             NaN            NaN             NaN  
1        14909.819             NaN            NaN             NaN  
2        15550.575             NaN            NaN             NaN  
3        15758.775             NaN            NaN             NaN  
4        17365.598             NaN            NaN             NaN  
5        17758.412             NaN            NaN             NaN  
6        18717.768             NaN            NaN             NaN  
7        20490.353             NaN            NaN             NaN  
8        20841.552             NaN            NaN             NaN  
9        21754.118             NaN            NaN             NaN  
10       21603.629             NaN            NaN             NaN  
11       22589.901             NaN            NaN             NaN  
12       22791.306             NaN            NaN             NaN  
13       22589.334             NaN            NaN             NaN  
14       20729.567             NaN            NaN             NaN  
15       21728.756             NaN            NaN             NaN  
16       21619.135             NaN            NaN             NaN  
17       21954.755             NaN            NaN             NaN  
18       22681.113             NaN            NaN             NaN  
19       23417.755             NaN            NaN             NaN  
20       24541.947           

In [13]:
# Enter in total amount you would like to invest under amountInvested 
amountInvested = 12000

In [67]:
# GENERATING MARKET PORTFOLIO
# format [U.S. Stocks, International Stocks, U.S. Bonds, International Bonds] (in billions for market cap)
EOQmarketcaps = np.array(etfEOQmarketcaps)
EOQprices = np.array(etfEOQprices)
recentPrices = np.asarray(etfRecentPrices)
# Market proportions for each etf on end of quarter
EOQproportions = EOQmarketcaps/sum(EOQmarketcaps)
# Ratio of recent prices and end of quarter prices
priceRatios = recentPrices / EOQprices
# Multiply ratios to market proportions
products = EOQproportions * priceRatios
# Market weights if fractional shares existed
revisedProportions = products / sum(products)
# Amount of money invested in each etf if fractional shares existed
desiredValues = revisedProportions * amountInvested
# Number of shares of etfs to buy if fractional shares existed
currentPrices = np.array(etfCurrPrices(['VTI', 'VXUS', 'BND', 'BNDX']))
shares = desiredValues/currentPrices
# Optimize to get as close to 0 since fractional shares with Schwab doesn't exist
def asdf(a):
    return amountInvested - sum(np.round(shares * a)*currentPrices)
a = .90
while asdf(a) > 0:
    if a <.99999:
        a+=.00001
    else:
        break
    if asdf(a) < 0:
        a-=.00001
        break
# Actual shares of each etf to buy
actualShares = np.round(shares * a)
print('VTI, VXUS, BND, BNDX')
print(actualShares)

NameError: name 'etfEOQmarketcaps' is not defined

In [15]:
actualProportions = (actualShares * currentPrices)/sum(actualShares * currentPrices)
print('Theoretical proportions')
print(revisedProportions)
print('Actual proportions')
print(actualProportions)

Theoretical proportions
[0.32022161 0.23760532 0.24689227 0.19528079]
Actual proportions
[0.31855103 0.23872327 0.24735598 0.19536972]


In [16]:
# Cash left over. You can invest this cash into VTIP (Vanguard's US TIPS ETF) or something else if you'd like.
cash = amountInvested - sum((actualShares * currentPrices))
print(np.round(cash,2))

0.29


In [17]:
# How much it costs to maintain portfolio per year
costs = [.0003,.0008,.00035,.0008]
print(sum((actualShares * currentPrices)*costs))

6.352818000000001


In [12]:
currentPrices

array([147.02,  45.47,  87.3 ,  57.18])

In [ ]:
# REBALANCE (run this cell if you already have money invested in the market portfolio)
# Enter in number of shares here in current port in the format of VTI, VXUS, BND, BNDX
currentPort = np.array([12.0588,27.0695,16.0667,21.0345])
trades = actualShares - currentPort
# Amount left for trades
amountInvestable = amountInvested - sum(currentPort * currentPrices)
# Need to make sure trades don't make balance go over amount of money available
def asdf(a):
    return amountInvestable - sum(np.round(trades * a)*currentPrices)
a = .90
while asdf(a) > 0:
    if a <.99999:
        a+=.00001
    else:
        break
    if asdf(a) < 0:
        a-=.00001
        break
actualTrades = np.round(trades * a)
print('Trades: VTI, VXUS, BND, BNDX')
print(actualTrades)
print()
print('Cash left over')
print(asdf(a))

In [ ]:
portAfterTrades = currentPort + actualTrades
print('Theoretical proportions')
print(revisedProportions)
print()
print('Actual proportions after rebalance')
print((portAfterTrades * currentPrices)/sum(portAfterTrades * currentPrices))